package org.example.heartbeat;

public enum HeartbeatEventType {
    LOAN_REQ, LOAN_RESP, CONSENT_REQ, CONSENT_RESP, LOAN_GEN_OFFER_REQ, LOAN_GEN_OFFER_RESP, LOAN_OFFER_REQ, LOAN_OFFER_RESP, TRIGGER_KYC_REQ, KYC_RESP, LOAN_ACCEPTANCE_REQ, LOAN_ACCEPTANCE_RESP, LOAN_REPAYMENT_REQ, LOAN_REPAYMENT_RESP, LOAN_REPAYMENT_CONF_RESP, LOAN_GRANT_REQ, LOAN_GRANT_RESP, LOAN_DISBURSMENT_REQ, LOAN_DISBURSMENT_RESP, LOAN_TRIGGER_DISBURSMENT_REQ, LOAN_TRIGGER_DISBURSMENT_RESP, LOAN_TRIGGER_REPAYMENT_REQ, LOAN_TRIGGER_COLLECTION_REQ
}
